### ISSUE TITLE
Request: Original models for re-mixing

### ISSUE THREAD

**Issue by bplein** [michaelriedl/Turing-Pi-2-Case#1]
Hello!

I love the case!

I was thinking of making my own Turing Pi 2 case, not related to yours, but would love to start with your I/O Plate so I don't have to start from scratch. 

Would you be willing to share any original models you built? I use Fusion 360 and can import several different formats.

Thanks!

**Comment by michaelriedl** [comment]
Glad you like it! I just added the Fusion 360 file. Enjoy!
